/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angga
 */
public class FormMahasiswa extends javax.swing.JInternalFrame {
    DefaultTableModel tabModel;
    ResultSet RsMahasiswa=null;
    
    List<String> jurusanList = new ArrayList<>();
    
    /**
     * Creates new form FormJurusan
     */
    public FormMahasiswa() {
        initComponents();
        
        dataCombobox();
 
        refreshTable();
    }
    
    private void refreshTable(){
        try{
            int total = 0;
            
            Object[] judul_kolom = {"#","Nim", "Nama", "Jurusan", "Telepon", "Alamat"};
            tabModel=new DefaultTableModel(null,judul_kolom);
            tbMahasiswa.setModel(tabModel);
            
            Connection conn=(Connection)KoneksiDB.koneksiDB();
            Statement stt=conn.createStatement();
            tabModel.getDataVector().removeAllElements();
            
            RsMahasiswa=stt.executeQuery("SELECT * from tb_mahasiswa JOIN tb_jurusan ON tb_mahasiswa.kode_jurusan = tb_jurusan.kode_jurusan");  
            while(RsMahasiswa.next()){
                Object[] data={
                    RsMahasiswa.getString("id"),
                    RsMahasiswa.getString("nim"),
                    RsMahasiswa.getString("nama"), 
                    RsMahasiswa.getString("nama_jurusan"), 
                    RsMahasiswa.getString("telepon"), 
                    RsMahasiswa.getString("alamat") 
                };
                tabModel.addRow(data);
                
                total++;
            }           
            
            totMahasiswa.setText("Total Mahasiswa: "+Integer.toString(total)+" Data");
            
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
        
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
    }
    
    public void dataCombobox(){
        try {
            Connection conn=(Connection)KoneksiDB.koneksiDB();
            Statement stt=conn.createStatement();
            String sql = "select * from tb_jurusan";
            ResultSet res=stt.executeQuery(sql);
            comboJurusan.addItem("-Pilih Jurusan-");
            while (res.next()) {
                String jurusan = res.getString(2);
                jurusanList.add(jurusan);
                comboJurusan.addItem(jurusan+" - "+res.getString(3));
            }
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }
    
    //membersihkan form
    private void BersihData(){
        txtNim.setText("");
        txtNama.setText("");
        comboJurusan.setSelectedIndex(0);
        txtTelepon.setText("");
        txtAlamat.setText("");
    } 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTambah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNim = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        txtTelepon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboJurusan = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbMahasiswa = new javax.swing.JTable();
        totMahasiswa = new javax.swing.JLabel();

        btnTambah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Tambah.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("DATA MAHASISWA");

        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Hapus.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Edit.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Batal.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nim");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Telepon");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Alamat");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Jurusan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNim, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addComponent(txtNama)
                    .addComponent(txtAlamat)
                    .addComponent(txtTelepon)
                    .addComponent(comboJurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        tbMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbMahasiswa);

        totMahasiswa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totMahasiswa.setText("Total Mahasiswa: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(totMahasiswa)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnBatal))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totMahasiswa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String nim=txtNim.getText();
        String nama=txtNama.getText();
        String jurusan=jurusanList.get(comboJurusan.getSelectedIndex() - 1);
        String telepon=txtTelepon.getText();
        String alamat=txtAlamat.getText();

        if (nim.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"Nim tidak boleh kosong");
            txtNim.requestFocus();
        }else if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Nama tidak boleh kosong");
            txtNama.requestFocus();
        }else if (jurusan.isEmpty()) {
            JOptionPane.showMessageDialog(null,"jurusan tidak boleh kosong");
            comboJurusan.requestFocus();
        }else if (telepon.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Telepon tidak boleh kosong");
            txtTelepon.requestFocus();
        }else if (alamat.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Alamat tidak boleh kosong");
            txtAlamat.requestFocus();
        }else{
            try{
                Connection conn=(Connection)KoneksiDB.koneksiDB();
                Statement stt=conn.createStatement();
                stt.executeUpdate("insert into tb_mahasiswa(kode_jurusan,nim,nama,telepon,alamat)"+
                    "VALUES('"+jurusan+"','"+nim+"','"+nama+"','"+telepon+"','"+alamat+"')");
                BersihData();
                refreshTable();
                JOptionPane.showMessageDialog(this,"Data berhasil disimpan","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Simpan data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String nim=txtNim.getText();

        if (nim.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"Nim tidak boleh kosong");
            txtNim.requestFocus();
        }else if(JOptionPane.showConfirmDialog(null,"Apakah anda yakin akan menghapus data ini?",
            "Informasi",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE)==JOptionPane.OK_OPTION){
            try{
                Connection conn=(Connection)KoneksiDB.koneksiDB();
                Statement stt=conn.createStatement();
                stt.executeUpdate("DELETE FROM tb_mahasiswa WHERE nim='"+nim+"'");
                BersihData();
                refreshTable();
                btnTambah.setEnabled(true);
                JOptionPane.showMessageDialog(this,"Data berhasil di hapus","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Delete data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String nim=txtNim.getText();
        String nama=txtNama.getText();
        String jurusan=jurusanList.get(comboJurusan.getSelectedIndex() - 1);
        String telepon=txtTelepon.getText();
        String alamat=txtAlamat.getText();

        if (nim.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"Nim tidak boleh kosong");
            txtNim.requestFocus();
        }else if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Nama tidak boleh kosong");
            txtNama.requestFocus();
        }else if (jurusan.isEmpty()) {
            JOptionPane.showMessageDialog(null,"jurusan tidak boleh kosong");
            comboJurusan.requestFocus();
        }else if (telepon.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Telepon tidak boleh kosong");
            txtTelepon.requestFocus();
        }else if (alamat.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Alamat tidak boleh kosong");
            txtAlamat.requestFocus();
        }else{
            try{
                Connection conn=(Connection)KoneksiDB.koneksiDB();
                Statement stt=conn.createStatement();
                int row = tbMahasiswa.getSelectedRow();
                String value = (tbMahasiswa.getModel().getValueAt(row, 0).toString());
                stt.executeUpdate("UPDATE tb_mahasiswa SET kode_jurusan='"+jurusan+"', nim='"+nim+"', nama='"+nama+"', telepon='"+telepon+"', alamat='"+alamat+"' WHERE id='"+value+"'");
                BersihData();
                refreshTable();
                btnTambah.setEnabled(true);
                JOptionPane.showMessageDialog(this,"Data berhasil diubah","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Ubah data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        refreshTable();
        BersihData();
        btnTambah.setEnabled(true);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void tbMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMahasiswaMouseClicked
        // TODO add your handling code here:
        try{
            Connection conn = KoneksiDB.koneksiDB();
            Statement stt = conn.createStatement();
            String sql = "SELECT kode_jurusan, nama_jurusan FROM tb_jurusan WHERE nama_jurusan='"+tabModel.getValueAt(tbMahasiswa.getSelectedRow(),3).toString()+"'";
            ResultSet res = stt.executeQuery(sql);
            if (res.next()) {
                comboJurusan.setSelectedItem(res.getString(1)+" - "+res.getString(2));
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
        
        txtNim.setText(tabModel.getValueAt(tbMahasiswa.getSelectedRow(),1).toString());
        txtNama.setText(tabModel.getValueAt(tbMahasiswa.getSelectedRow(),2).toString());
        txtTelepon.setText(tabModel.getValueAt(tbMahasiswa.getSelectedRow(),4).toString());
        txtAlamat.setText(tabModel.getValueAt(tbMahasiswa.getSelectedRow(),5).toString());

        btnTambah.setEnabled(false);
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);
        btnBatal.setEnabled(true);
    }//GEN-LAST:event_tbMahasiswaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> comboJurusan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbMahasiswa;
    private javax.swing.JLabel totMahasiswa;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtTelepon;
    // End of variables declaration//GEN-END:variables
}